### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by paullemmens** [ristomatti/gmail-solarized-dark#1]
Hi I've just found your repo but have not yet been able to figure out how to use your CSS to style/theme Gmail. I did see that you have other apps solarized as well but, for instance, Trello runs via Stylish. Could I use this CSS without going through that site/extension?

**Comment by ristomatti** [comment]
Hi!

I'm happy to hear you have noticed I've got multiple Solarized inspired themes (although modified to have dark grey background instead of the typical blue background color) as you're the first one to mention it! Unfortunately I have to say this one is something I've since abandoned. If I remember correctly also never published on userstyles.org as I never got it to a level I'm happy with myself. Theming Gmail turned out to be too difficult to get right as all the CSS classes seem random generated and change too often.

As I don't like having a white background color on any of the sites I use on a daily basis I had to resort to an alternative approach with Gmail. What I've done instead is set the :black theme from Gmail settings and then use a Stylish theme on top of that, which is based on how the Dark Reader Chrome extension modifies the colors (basically inverting them). I've just tweaked the CSS to only have an effecr on the sections that are left with a white background color. This has worked nicely for many months although it's not Solarized themed..In case you're interested to try it, I can attach the CSS øn this issue?

P.S. Today is the Midsummer celebration day here in Finland so please excuse me if the above reply was somewhat incoherent. It was written on a phone with the help of Swift Keyboard autocorrect. Just before going to sleep..

**Comment by paullemmens** [comment]
Hi, thnx for getting back to me so soon! I already tried a few other
generic and dedicated themes from userstyles and came to the same
conclusion. So i'll try and work from your description first and if i need
further help i'll contact you again.

Thnx

**Comment by ristomatti** [comment]
@paullemmens Wow I didn't even remember ever making this repository, even less that there was an issue thread. 😂

Nowadays I use the Dark Reader extension (and a few userstyle tweaks).
